### ISSUE TITLE
Start transaction vs API versions

### ISSUE THREAD

**Issue by fruitl00p** [paynl/sdk#41]
After some back-and-forth with our client it seems the (current) SDK differs quite a bit (v5) with the (latest) API version (v7). Is there a comprehensive changelog between the two or will the SDK be updated to support the latest API version? 

Having to juggle the version and possible changes manually seems error prone and difficult... 

Is it possible to align the SDK releases with updates according to spec (https://admin.pay.nl/docpanel/api) ?

**Comment by andypieters** [comment]
Iam not sure which namespace you are referring to, but iam guessing the Transaction namespace.
Actually the sdk uses v6 the lates version is v7.
In our API every namespace has its own version.
The version gets updated if in one of the api functions a breaking change is introduced.
Older versions will still be supported.
When there is a need to update the api version, i will update it, but most functions the sdk uses haven't changed since v3.
