### ISSUE TITLE
Undefined index: refundId

### ISSUE THREAD

**Issue by BBrunekreeft** [paynl/sdk#54]
Getting the RefundID after a refund gives me an Undefined index.
`$result = \Paynl\Transaction::refund($transactionID, $amount, $description);`
`$refundID = $result->getRefundId();`

throws
`PHP Notice 'yii\base\ErrorException' with message 'Undefined index: refundId'`
`in /data/www/html/administratie/vendor/paynl/sdk/src/Result/Transaction/Refund.php:35`

This stopped working after version 1.5.2

**Comment by sashaskr** [comment]
I tried to reproduce an issue in tests. I got the same result. Test below, added to `TransactionTest.php` will generate the same error.
```
    public function testIssueNumber54()
    {
        \Paynl\Config::setApiToken('123456789012345678901234567890');
        $this->setDummyData('Result/transactionPaid');

        $transaction = Paynl\Transaction::get('645958819Xdd3ea1');

        $refund = \Paynl\Transaction::refund($transaction->getId(), 5, 'Description');

        $this->assertInstanceOf('Paynl\Result\Transaction\Refund', $refund);
        $this->assertStringStartsWith('RF-', $refund->getRefundId());
    }
```
I suppose it is about the same case of @BBrunekreeft

**Comment by andypieters** [comment]
@sashaskr 
That is because you are setting the wrong response as dummy data.
You should use the dummy response: $this->setDummyData('Result/refund');

There is already a test for this: https://github.com/paynl/sdk/blob/master/tests/TransactionTest.php#L223-L232

What you are testing are 2 different api calls.
The first one gets the transaction from pay.nl, the second will refund it.
If you want to test it in this way, you could do it like this:

```
public function testIssueNumber54()
    {
        \Paynl\Config::setApiToken('123456789012345678901234567890');
        $this->setDummyData('Result/transactionPaid');

        $transaction = Paynl\Transaction::get('645958819Xdd3ea1');

        $this->setDummyData('Result/refund');

        $refund = \Paynl\Transaction::refund($transaction->getId(), 5, 'Description');

        $this->assertInstanceOf('Paynl\Result\Transaction\Refund', $refund);
        $this->assertStringStartsWith('RF-', $refund->getRefundId());
    }
```

**Comment by sashaskr** [comment]
@andypieters Thank you for your reply. My idea was to have a transaction and refund it without setting the dummy data for the refund. In the real situation, I can make a `Paynl\Result\Transaction\Refund` object only if I have a transaction. When I am tracing this call, I can see 2 calls of `doRequest()` methods. 1st one is passed because of dummy data is set, but the 2nd one is generating an error `Undefined index: refundId`. Is it make sense to have an additional check for this error exception with setting an error with message and code? I found this error is returning only if 2nd `doRequest()` fails. Looks like it happens if API call not Authorised with 401 error.

**Comment by BBrunekreeft** [comment]
@andypieters, do you know why my code works fine with version 1.5.2, but gives me the undefined index message with version 1.5.3 and up?
Does it have something to do with moving from transaction API v8 to transaction API v12?

**Comment by andypieters** [comment]
@BBrunekreeft Found it, you were right, it has to do with v12 of the api.
v12 no longer returns a refund id, but a collection of refunded transactions (in case of voucher payments)
I'll have to change the result for this api, i can no longer have 1 refundId

**Comment by BBrunekreeft** [comment]
@andypieters, is this going to be fixed in an upcoming release?

**Comment by BBrunekreeft** [comment]
This issue has been solved in the latest release (https://github.com/paynl/sdk/releases/tag/v1.5.11) 
Thanks!
